services:
  # API
  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    container_name: portfolio-api
    ports:
      - "3001:3001"
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules
      - ../api/prisma:/usr/src/app/prisma
    environment:
      - DATABASE_URL=file:/usr/src/app/dev.db
      - JWT_SECRET=${JWT_SECRET:-dfff9d0f5f5c9745b90b8d392bd2e7e0}
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    working_dir: /usr/src/app
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run dev
      "
    restart: unless-stopped