version: '3.8'

services:
  # API
  api:
    build:
      context: ../api
      dockerfile: Dockerfile  # Usa o Dockerfile de produção
    container_name: portfolio-api-prod
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:/usr/src/app/dev.db
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    volumes:
      - db_data:/usr/src/app/dev.db  # Persiste o banco de dados
    restart: always

volumes:
  db_data: